name: Test Deno Module

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v1.x, vx.x.x]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v3.1.0
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Lint Deno Module
        run: deno fmt --check
      - name: Test Deno Module
        run: deno test --allow-none
